version: '3.8'

services:
  my_service:
    entrypoint: "/bin/bash"
    image: 691be48bc6a4 # 사용하고자 하는 Docker 이미지 이름
    container_name: testCon
    volumes:
      - .:/workspace # 호스트와 컨테이너 간의 디렉토리 마운트
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 소켓 마운트
    environment:
      - DISPLAY=host.docker.internal:0 # X11 디스플레이 환경 변수 설정
    cap_add:
      - SYS_ADMIN # 추가적인 권한 부여
    network_mode: "host" # 호스트 네트워크 모드 설정
    stdin_open: true
    tty: true
